# ensure directory exists
- name: Ensure directory exists
  ansible.builtin.file:
    path: '{{ paths.root }}/{{ role_name }}'
    state: directory

# configure magicmirror
- name: Create configuration
  ansible.builtin.template:
    src: '{{ role_name }}/config.yml.j2'
    dest: '{{ paths.root }}/{{ role_name }}/config.yml'
    validate: docker run --rm -v %s:/etc/{{ role_name }}/config.yml ghcr.io/pascaliske/{{ role_name }}:latest config validate

# create container
- name: Create container
  community.docker.docker_container:
    name: '{{ role_name }}'
    image: ghcr.io/pascaliske/magicmirror:1.0.0
    restart_policy: unless-stopped
    pull: true
    ports:
      - "{{ url | urlsplit('port') }}:{{ url | urlsplit('port') }}"
    env:
      TZ: '{{ timezone }}'
    mounts:
      - type: bind
        source: '{{ paths.root }}/{{ role_name }}'
        target: /etc/{{ role_name }}
