image:
  file: .gitpod.Dockerfile

tasks:
  - name: dependencies
    before: go install github.com/mitranim/gow@latest
    init: yarn install && gp sync-done install
  - name: app
    init: gp sync-await install
    command: yarn start
    openMode: tab-after
  - name: server
    init: gp sync-await install
    command: yarn start:server
    openMode: split-right

ports:
  - port: 9000
    onOpen: notify
  - port: 4200
    onOpen: notify

vscode:
  extensions:
    - angular.ng-template
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - golang.Go
    - ms-azuretools.vscode-docker
    - tyriar.sort-lines

github:
  prebuilds:
    master: true
    addComment: true
