# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  vault: ./.github/taskfiles/vault.yml
  docs: ./.github/taskfiles/docs.yml

tasks:
  install:
    summary: Install all related dependencies
    cmds:
      - yarn install
      - cd ansible && ansible-galaxy install -r requirements.yml
      - cd server && go mod tidy

  start:app:
    summary: Start the frontend app in development mode
    cmds:
      - ng serve

  start:api:
    summary: Start the API in development mode
    dir: api
    interactive: true
    cmds:
      - gow run -ldflags="$GO_LDFLAGS" main.go --config ../config.yml serve {{.CLI_ARGS}}

  run:api:
    summary: Run API commands in development mode
    dir: api
    cmds:
      - go run -ldflags="$GO_LDFLAGS" main.go --config ../config.yml {{.CLI_ARGS}}

  build:api:
    summary: Build the API for testing purposes
    dir: api
    cmds:
      - go build -v -ldflags="$GO_LDFLAGS" -o ../magicmirror main.go {{.CLI_ARGS}}

  docker:build:
    summary: Build the Docker image for testing purposes
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} --build-arg=MM_VERSION={{.VERSION}} --build-arg=MM_GIT_COMMIT={{.GIT_COMMIT}} --build-arg=MM_BUILD_TIME={{.BUILD_TIME}} .
    vars:
      DOCKER_IMAGE: ghcr.io/pascaliske/magicmirror:dev
      VERSION:
        sh: git symbolic-ref -q --short HEAD || git describe --tags --exact-match | tr -d v
      GIT_COMMIT:
        sh: git rev-list -1 HEAD
      BUILD_TIME:
        sh: date -u +%Y-%m-%dT%H:%M:%SZ

  provision:
    summary: Provision the target host using Ansible
    dir: ansible
    interactive: true
    cmds:
      - ansible-playbook --diff --extra-vars @vars/vault.yml playbooks/provision.yml

  update:
    summary: Update the target host using Ansible
    dir: ansible
    interactive: true
    cmds:
      - ansible-playbook --diff --extra-vars @vars/vault.yml playbooks/update.yml

  ssh:
    summary: SSH into target host
    interactive: true
    cmds:
      - ssh -t -i "$ANSIBLE_PRIVATE_KEY_FILE" "$SSH_USER@$SSH_HOST" {{.CLI_ARGS}}

  docs:
    summary: Documentation specific tasks.
    cmds:
      - task: docs:default
