- name: Provision host
  hosts: all
  roles:
    - role: common
      tags:
        - common
    - role: tailscale
      tags:
        - tailscale
    - role: magicmirror
      tags:
        - magicmirror
    - role: watchtower
      tags:
        - watchtower
