---
- name: provision
  hosts: all
  roles:
    - role: common
      tags:
        - common
    - role: magicmirror
      tags:
        - magicmirror
    - role: watchtower
      tags:
        - watchtower
