# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  encrypt:
    summary: Encrypt Ansible vault file
    dir: ansible
    interactive: true
    cmds:
      - ansible-vault encrypt vars/vault.yml

  decrypt:
    summary: Decrypt Ansible vault file
    dir: ansible
    interactive: true
    cmds:
      - ansible-vault decrypt vars/vault.yml
