name: Build Docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v5

      # setup taskfile
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # create pages for docs
      - name: Create pages for docs
        run: task docs

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
